version: '3.9'

services:
  database:
    image: mysql:8
    container_name: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: lmsc
      MYSQL_DATABASE: lmsc-db
      MYSQL_USER: user
      MYSQL_PASSWORD: lmsc
      TZ: Asia/Tokyo
    ports:
        - 3306:3306
    volumes:
        - ./lmsc_database/init_db:/docker-entrypoint-initdb.d
    networks:
      - lmsc_local

  front:
    build:
      context: "./lmsc_front"
      dockerfile: "Dockerfile" 
    volumes:
      - ../../Server-Front/lmsc/nuxt-app/:/app
      - ../../Server-Front/environment/develop:/etc
    ports:
      - '3000:3000'
    environment:
      - HOST=0.0.0.0
    stdin_open: true
    tty: true
  
  fast-api:
    build:
      context: "./lmsc_api"
      dockerfile: "Dockerfile" 
    depends_on:
      - database
    ports:
      - 443:443
    volumes:
      - ../../Server-API/app:/app
      - ../../Server-API/environment/develop:/etc
    networks:
      - lmsc_local

volumes:
  db-store:

networks:
  lmsc_local:
    name: lmsc_local

